version: '3'
services:
  reverse-proxy: # NGINX
    image: nginx:1.21.1 # image with S.O
    container_name: reverse-proxy-container 
    volumes: # association of config file from the host to the container
      - ./nginx/nginx-conf.conf:/etc/nginx/nginx.conf 
    depends_on:
      - api-gateway
      - bot
    ports:
      - 5000:80 #Host:Container (Check nginx-conf.confg; container port is the same as what NGINX is listening to)
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
      target: dev
    image: api-gateway
    volumes:
      - ./api-gateway:/api-gateway
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
      target: dev
    image: bot
    volumes:
      - ./bot:/bot
      - /bot/node_modules

  
