version: '3.4'

services:
  reverse-proxy: # NGINX
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: tetusrocus/nginx
    container_name: reverse-proxy-container
    environment:
      COMPOSE_PROJECT_NAME: 'ClanBot'
    ports:
      - 5000:80 #Host:Container (Check nginx-conf.confg; container port is the same as what NGINX is listening to)
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
      target: production
    image: tetusrocus/bot
    environment:
      COMPOSE_PROJECT_NAME: 'ClanBot'

  python-api:
    build:
      context: ../BotPython
      dockerfile: Dockerfile
    image: tetusrocus/python-api
    restart: always
    environment:
      COMPOSE_PROJECT_NAME: 'ClanBot'
      PYTHONUNBUFFERED: 1

