apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: tetusrocus/nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      restartPolicy: Always
      # nodeSelector:
      #   node.role.kubernetes.io/worker: worker

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 31000
  selector:
    # apply service to any pod with label app: nginx
    app: nginx

